### ISSUE TITLE
Configuring a Dictionary

### ISSUE THREAD

**Issue by hounddog22030** [aws/aws-dotnet-extensions-configuration#104]
## The Question
Does this library support dictionary values like described in [this article](https://andrewlock.net/how-to-use-the-ioptions-pattern-for-configuration-in-asp-net-core-rc2/)? 

In the example, the configuration options are initialized via 

`services.Configure<MySettings>(options => Configuration.GetSection("MySettings").Bind(options));`

I have a class as below:

`
public class QueueConfiguration
{
    public Dictionary<string,string> Uris { get; set; }
}
`
and I issue:

`
serviceCollection.Configure<QueueConfiguration>(configuration.GetSection(nameof(QueueConfiguration)))
`
but my Dictionary of `Uris` is always empty.

I have a SSM Parameter of `/system/blue-green/block-ssm/green/QueueConfiguration/Uris/SqsEventHandlerAsyncYadaYadaBubbleBoyWebApiFunctionsMasterFunctionQueue`

and `/system/blue-green/block-ssm/green` is configured as the path via AddSystemsManager()

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @hounddog22030,

Good morning.

Thanks for creating guidance issue. Using your model/use case as starting point and ASP.NET Core WebApi project template, I was able to retrieve list of _Uris_ as  a dictionary using the [Amazon.Extensions.Configuration.SystemsManager](https://www.nuget.org/packages/Amazon.Extensions.Configuration.SystemsManager/) package. Here is the source:
**Startup.cs**
```C#
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace ParameterStoreDictionaryTest
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.Configure<QueueConfiguration>(Configuration.GetSection("QueueConfiguration"));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
}
```
Kindly note the addition of `services.Configure<QueueConfiguration>(Configuration.GetSection("QueueConfiguration"));` in `ConfigureServices()`.
**Program.cs**
```C#
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;

namespace ParameterStoreDictionaryTest
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((context, builder) => {
                    builder.AddSystemsManager("/system/blue-green/block-ssm/green");
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}
```
**ValuesController.cs**
```C#
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace ParameterStoreDictionaryTest.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class ValuesController : ControllerBase
    {
        private readonly IOptions<QueueConfiguration> _queueConfiguration;

        public ValuesController(IOptions<QueueConfiguration> queueConfiguration)
        {
            _queueConfiguration = queueConfiguration;
        }

        // GET api/values
        [HttpGet]
        public ActionResult Get()
        {
            return Ok(new
            {
                QueueConfiguration = _queueConfiguration.Value
            });
        }
    }
}
```
**.csproj* file
```XML
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Extensions.Configuration.SystemsManager" Version="3.0.0" />
  </ItemGroup>


</Project>
```
**QueueConfiguration.cs**
```C#
using System.Collections.Generic;

namespace ParameterStoreDictionaryTest
{
    public class QueueConfiguration
    {
        public Dictionary<string, string> Uris { get; set; }
    }
}
```
**RESULT:** _QueueConfiguration.Uris_ has values in a dictionary:
<img width="1264" alt="Screen Shot 2022-02-15 at 11 31 32 AM" src="https://user-images.githubusercontent.com/67916761/154136055-45e2d425-d32c-42d9-a2e1-7bf9c0672330.png">

Could you please check if you added` services.Configure<QueueConfiguration>(Configuration.GetSection("QueueConfiguration"));` in `ConfigureServices()`? Please let me know if anything else is required.

Thanks,
Ashish

**Comment by hounddog22030** [comment]
So sorry, about three hours after posting this, I found an async call without an await and that was the issue.  I typically try to be a good citizen and close issues if I find it was because of another problem, but it was 2:00 am and I was tired.  But, at least there's a great example for someone.  Again, sorry and thanks.
