### ISSUE TITLE
Unable to load params from AWS Param Store

### ISSUE THREAD

**Issue by viresh323** [aws/aws-dotnet-extensions-configuration#109]
Hi Team,

My application is not able to talk to AWS Param Store in .NET 6. It is always talking to appsettings.json. Can you  take a look please. I tried debugging locally, still same behavior. Not able to find the SystemManagerConfiguration under list of configuration .

![image](https://user-images.githubusercontent.com/8353838/156374584-4d523448-ba18-4bfb-bb65-412572f2a640.png)

`var builder = WebApplication.CreateBuilder();`
`var connectionString = builder.Configuration.GetConnectionString("OrderTrackerDatabase");`

![image](https://user-images.githubusercontent.com/8353838/156374456-e90ea336-2a2e-41d2-b418-fa4be6b68495.png)

Expected Behavior : Configuration must be loaded from AWS Param Store
Current Behavior : Configuration is loaded from appsettings.json

Your Environment
![image](https://user-images.githubusercontent.com/8353838/156373923-dfd31a90-b19e-49ee-845c-63a5e4f8521a.png)

Output of dotnet --info:
`.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  2.2.103 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  5.0.405 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]`

Thanks,
Viresh

**Comment by viresh323** [comment]
Hi @ashishdhingra ,

Sorry.. You can ignore builder.Build() - nothing relevant to this., forgot to remove that part while taking snapshot.

I do have the access to that resource, in case of authentication issue - I guess CreateHostBuilder function will throw error (image) but that doesn't happen to me. Is there anything that you want me to try out while debugging? I'm using net6.0 - does it have an impact?
![image](https://user-images.githubusercontent.com/8353838/156421429-a501ce8e-7ed3-4cd6-9c7a-c6e67a3ba1fd.png)

**Comment by ashishdhingra** [comment]
> Hi @ashishdhingra ,
> 
> Sorry.. You can ignore builder.Build() - nothing relevant to this., forgot to remove that part while taking snapshot.
> 
> I do have the access to that resource, in case of authentication issue - I guess CreateHostBuilder function will throw error (image) but that doesn't happen to me if I give correct access keys. Is there anything that you want me to try out while debugging? I'm using net6.0 - does it have an impact? ![image](https://user-images.githubusercontent.com/8353838/156421429-a501ce8e-7ed3-4cd6-9c7a-c6e67a3ba1fd.png)

@viresh323 Please assess on how your credentials are configured locally. Kindly refer [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html) for guidance. In your case, it is failing at the end `Amazon EC2 instance metadata` after failing to find credentials at all locations (which would obviously fail in non-EC2 instance).

**Comment by viresh323** [comment]
@ashishdhingra , I believe my credentials are correct and has appropriate permission. This is how I verified.

.credentials : 
![image](https://user-images.githubusercontent.com/8353838/156496510-24cc3169-3036-41bc-b572-8639f0af5039.png)

I used this profile to troubleshoot locally..
With same role and account - I'm able to view/add/update the params in the AWS Console Paramater Store. Also -  verified the IAM Permission policies - it has Describe/GetParameter action for resource parameter/*

The screenshot (Amazon EC2 instance metadata) that I sent was just a demonstration of error when there is something wrong with the credentials. That isn't actual issue cause, I mocked it up. 

Actual issue is not able to see "SystemManager" configuration in the list of Configuration. 
![image](https://user-images.githubusercontent.com/8353838/156497991-17ce0f12-8de5-4646-bcb5-38ce19359a31.png)

**Comment by viresh323** [comment]
SystemManager configuration is present while creating host 

![image](https://user-images.githubusercontent.com/8353838/156501388-32c62c32-1642-4ffe-8397-95e49d0bf95f.png)


But not present at the point of getting configuration..

![image](https://user-images.githubusercontent.com/8353838/156501471-84a1e548-56ec-4d32-8fbb-0272d8cccefc.png)

**Comment by viresh323** [comment]
@ashishdhingra I figured it out, looks like WebApplication.CreateBuilder() is creating new instance every time and doesn't carry over the SystemManager configuration. 

Instead, I used IConfiguration instance to fetch the configuration

Thanks for taking a look. @ashishdhingra
