### ISSUE TITLE
"AddSystemsManager" method doesn't work with DI and .Net 6

### ISSUE THREAD

**Issue by zhlei616** [aws/aws-dotnet-extensions-configuration#114]
### Describe the bug

Hi there,
My issue is similar with the one below which found by another developer - 
https://stackoverflow.com/questions/71324248/c-sharp-aws-parameter-store-configuration-not-loading-systemmanagerconfigurati/72710278

From the sample code, it created and loaded parameters successfully in "PopulateSampleDataForThisProject" method (this means there's no issue with my AWS account), "AddSystemsManager" method was also called successfully however when consuming those settings in "ValuesController", the setting values are always default values of each data type not the values from AWS parameter store.
Initially I thought it was issue of my code, however after checked out this code repo, the same issue happens for "Samples" project as well.

Is this related to .Net 6?

### Expected Behavior

"AddSystemsManager" method should work with DI, setting values loaded from AWS Parameter Store should be available when cumsuming "IOptions Settings" in project.

### Current Behavior

"AddSystemsManager" method loaded parameters from AWS successfully (I can see those values from builder's configuration providers), however when consuming "IOptions Settings" in project, the settings values are not the values from AWS Parameter Store, so it's sth. wrong with DI

### Reproduction Steps

1. Using "Samples" project in this code repo
2. Run the project, the parameters defined "PopulateSampleDataForThisProject" method are created and loaded successfully
3. Open "ValuesController" in web browser, the setting values are just default value of each data type, not the values loaded from AWS Parameter Store

### AWS .NET SDK and/or Package version used

Amazon.Extensions.Configuration.SystemsManager 3.0.0

### Targeted .NET Platform

.Net 6

### Operating System and version

Windows 10

**Comment by zhlei616** [comment]
OK, I found the reason now, the "Samples" project missed one line of code as below - 
`
builder.Services.Configure<Settings>(builder.Configuration.GetSection($"common:settings"));
`
After added above line, it works as expected.

**Comment by viresh323** [comment]
This is other thread where issue was pointed out and a fix was provided, making it visible for others to discuss which is better way of solving this.
https://github.com/aws/aws-dotnet-extensions-configuration/issues/109#issuecomment-1057714536

**Comment by ashishdhingra** [comment]
> OK, I found the reason now, the "Samples" project missed one line of code as below - `builder.Services.Configure<Settings>(builder.Configuration.GetSection($"common:settings"));` After added above line, it works as expected.
> 
> I don't have permission to publish new feature branch in this code repo, otherwise would create a PR to fix this issue.

@zhlei616 Just to reconfirm, the sample application needs an update to fix the issue. Is this correct? You should be able to fork the repo and then create the PR.

Thanks,
Ashish

**Comment by zhlei616** [comment]
> > OK, I found the reason now, the "Samples" project missed one line of code as below - `builder.Services.Configure<Settings>(builder.Configuration.GetSection($"common:settings"));` After added above line, it works as expected.
> > I don't have permission to publish new feature branch in this code repo, otherwise would create a PR to fix this issue.
> 
> @zhlei616 Just to reconfirm, the sample application needs an update to fix the issue. Is this correct? You should be able to fork the repo and then create the PR.
> 
> Thanks, Ashish

@ashishdhingra , yes the "SystemManager" project itself is fine, the issue is in "Samples" project only.
I've created a PR for this - https://github.com/aws/aws-dotnet-extensions-configuration/pull/115

**Comment by zhlei616** [comment]
Issue has been fixed in https://github.com/aws/aws-dotnet-extensions-configuration/pull/115 which has been merged.
