### ISSUE TITLE
Missing documentation for loading Secret Manager secrets as SSM parameters

### ISSUE THREAD

**Issue by albertocorrales** [aws/aws-dotnet-extensions-configuration#121]
### Describe the issue

Looking at the implementation of this library, we can load secrets from Secrets Manager as SSM parameters, based on this documentation: https://docs.aws.amazon.com/systems-manager/latest/userguide/integration-ps-secretsmanager.html

However, this is not mentioned in the documentation of the library. In order to make it work, it would be good to describe the particularities to work secrets manager, like:
- You have to use as path the following format `/aws/reference/secretsmanager/secret_ID_in_Secrets_Manager`
- You cannot use wildcards, you will need an entry per secret
- In your secret, you have to define one or multiple key-value entries, which will be loaded as a configuration in the dotnet app. Adding an example would help to understand this point.

### Links

This file should contain the documentation mentioned above: https://github.com/aws/aws-dotnet-extensions-configuration/blob/master/README.md

Then, for this file https://github.com/aws/aws-dotnet-extensions-configuration/blob/master/src/Amazon.Extensions.Configuration.SystemsManager/SystemsManagerExtensions.cs, it would be good to remove that SecretsManager is not supported, because it is actually supported.

**Comment by ashishdhingra** [comment]
@albertocorrales Thanks for submitting the issue. Since you have already tested the library with secrets manager, please advise if it would be possible for you to submit the PR to make the documentation change along with example.

**Comment by ashishdhingra** [comment]
Readme has been updated to add details for referencing secrets from AWS Secrets Manager from Parameter Store parameters. The code documentation comments are fixed in [Amazon.Extensions.Configuration.SystemsManager version 5.0.3](https://www.nuget.org/packages/Amazon.Extensions.Configuration.SystemsManager/5.0.3).
