### ISSUE TITLE
Loading AppConfig feature flags into strong-type options

### ISSUE THREAD

**Issue by icelava** [aws/aws-dotnet-extensions-configuration#125]
### Describe the issue

So I've defined a feature flag configuration profile in AppConfig with two booleans e.g.

- Run = true
- Jump = false

For the ASP.NET 6 WebApplicationBuilder.Configuration object, it gets extended with AppConfig.

```
var builder = WebApplication.CreateBuilder(args);
builder.Configuration.AddAppConfig("appid", "envid", "configprofileid", TimeSpan.FromSeconds(30));

// This will not work.
// builder.Services.Configure<FeatureFlags>(builder.Configuration.GetSection(nameof(FeatureFlags)));
```

But how to read in all those feature flags into a consolidated options object? There's no real configuration section tied to those, is there?

```
public class FeatureFlags
{
	public bool Run { get; set; }
	public bool Jump { get; set; }
}

public class AppConfigModel : PageModel
{
	internal FeatureFlags FeatureFlags{ get; private set; }

	public AppConfigModel(IOptionsSnapshot<FeatureFlags> flagOptions)
	{
		this.FeatureFlags= flagOptions.Value;
	}

	public void OnGet()
	{
	}
}
```

### Links

https://github.com/aws/aws-dotnet-extensions-configuration

**Comment by ashishdhingra** [comment]
@icelava Thanks for opening the issue. Could you please share screenshot(s) on what your AppConfig in AWS Console looks like and how you have defined a feature flag configuration profile in `AppConfig` with two booleans e.g.
- Run = true
- Jump = false

Thanks,
Ashish

**Comment by icelava** [comment]
It's just a feature flag config profile with flags defined.

![AWS AppConfig feature flags](https://user-images.githubusercontent.com/1930886/202987185-03819805-17b6-4cbb-9e1b-837614ab89aa.JPG)

**Comment by ashishdhingra** [comment]
> It's just a feature flag config profile with flags defined.
> 
> ![AWS AppConfig feature flags](https://user-images.githubusercontent.com/1930886/202987185-03819805-17b6-4cbb-9e1b-837614ab89aa.JPG)

@icelava Just for reference, debugged using the clone of the repository and defining the flags similar to your screenshot. The configuration is returned as a dictionary like below:
<img width="360" alt="Screen Shot 2022-11-22 at 10 34 53 AM" src="https://user-images.githubusercontent.com/67916761/203397800-0d332f0e-1a07-4392-ac12-1561766266a4.png">

**Comment by icelava** [comment]
So supposed to be configuring for a Dictionary<sting, bool> object instead? But what's the configuration section name?

`builder.Services.Configure<Dictionary<string, bool>>(builder.Configuration.GetSection("WHATCONFIGSECTIONNAME"));`

If I place in the name of the configuration profile as config section name "FeatureFlags", all the page gets on construction is just an IOptionsSnapshot<Dictionary<string, bool>> of an empty dictionary.

**Comment by icelava** [comment]
Ok now that have some spare time to revisit this issue, I found that given the nature of the config parameter names returned from AppConfig to ASP.NET, it's not possible to consolidate all feature flags in one configuration profile into the same .NET strong-typed config object.

The class has to be written for each individual feature flag.
```
public class FeatureFlagRun
{
	public bool Enabled { get; set; }
}
```

Then the configuration builder draws in the feature flag as the "Run" config section alone.
`builder.Services.Configure<FeatureFlagRun>(builder.Configuration.GetSection("Run"));`

Given that this has to be done repeatedly for each feature flag, think it's just way more convenient to use free-form JSON.
