### ISSUE TITLE
AddSystemsManager with SecretsManager path resolves parameters with ':' prefix

### ISSUE THREAD

**Issue by Paulskit** [aws/aws-dotnet-extensions-configuration#133]
### Describe the bug

Hello Amazon,
I've updated to 5.0.0 Amazon.Extensions.Configuration.SystemsManager and having issues with loading data from SecretsManager.

Keys in the stored object is resolved with ':' prefix.

### Expected Behavior

Similar to 4.0.0, keys should be provided as written in json stored in Secret

### Current Behavior

![image](https://user-images.githubusercontent.com/9947675/221620399-4fd2ac1e-a5c4-4aa1-ae09-7acbb47d1440.png)

### Reproduction Steps

1) Store secret in SecretsManager
2) Load it with 
```csharp
.AddSystemsManager(source => {
  source.Path = $"/aws/reference/secretsmanager/{secretName}";
  source.Prefix = string.Empty;
});
``` 
3) Notice keys in secret contain `:` as prefix.

### Additional Information/Context

Possibly introduced by #130 

### AWS .NET SDK and/or Package version used

Amazon.Extensions.Configuration.SystemsManager 5.0.0

### Targeted .NET Platform

.NET 6

### Operating System and version

OSX Ventura 13.1, Amazon Linux 2

**Comment by ashishdhingra** [comment]
**Repro Steps:**
1. Using secrets manager, create a database secret names `TestSecret`.
2. In ASP.NET web application, use the following code to add system manager source:

```C#
builder.Configuration.AddSystemsManager(source =>
{
    source.ParameterProcessor = new JsonParameterProcessor();
    source.Path = $"/aws/reference/secretsmanager/TestSecret";
});

```

**Comment by ashishdhingra** [comment]
This should be fixed in [Amazon.Extensions.Configuration.SystemsManager 5.0.1](https://www.nuget.org/packages/Amazon.Extensions.Configuration.SystemsManager/5.0.1).
