### ISSUE TITLE
Missing dependency AWSSDK.SecurityToken ?

### ISSUE THREAD

**Issue by peabnuts123** [aws/aws-dotnet-extensions-configuration#141]
### Describe the bug

Our application crashes with a runtime dependency error for `AWSSDK.SecurityToken` when trying to call `AddSystemsManager()` 

### Expected Behavior

No errors.

### Current Behavior

When attempting to deploy this to our testing environment, our application stops working with the following error:

```
Unhandled exception. System.InvalidOperationException: Assembly AWSSDK.SecurityToken could not be found or loaded. This assembly must be available at runtime to use Amazon.Runtime.AssumeRoleAWSCredentials.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'AWSSDK.SecurityToken, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'AWSSDK.SecurityToken, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.<InternalLoad>g____PInvoke|47_0(NativeAssemblyNameParts* pAssemblyNameParts, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Int32 throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Amazon.Runtime.Internal.ServiceClientHelpers.GetSDKAssembly(String assemblyName)
…
```

Worth noting that it works okay on my machine™, but is only once we deploy to our k8s-based environment that this error occurs. This is not the case if I run the same docker image that is run in k8s locally - that works fine too 🤔

### Reproduction Steps

This is the code I have in my application:
```csharp
builder.Configuration.AddSystemsManager((options) =>
{
    options.Path = "/Prefix/For/My/Application";
    options.OnLoadException += exceptionContext =>
    {
        Console.Error.WriteLine("Error occurred while reading configuration from Parameter Store:");
    };
});
```

I am simply using it in the most basic manner. 

### Possible Solution

After installing the dependency `AWSSDK.SecurityToken` manually, the issue goes away. It seems like there may be a [missing dependency](https://github.com/aws/aws-dotnet-extensions-configuration/blob/master/src/Amazon.Extensions.Configuration.SystemsManager/Amazon.Extensions.Configuration.SystemsManager.csproj#L47) on `AWSSDK.SecurityToken` in this project? 

### Additional Information/Context

There are [other comments on here reporting similar behaviour](https://github.com/aws/aws-dotnet-extensions-configuration/issues/61#issuecomment-709315324). 

### AWS .NET SDK and/or Package version used

```<PackageReference Include="Amazon.Extensions.Configuration.SystemsManager" Version="5.0.2" />```

### Targeted .NET Platform

ASP.NET 7

### Operating System and version

Docker image: mcr.microsoft.com/dotnet/aspnet:7.0

**Comment by peabnuts123** [comment]
Thanks for the clarification @normj. Is there anywhere this is documented? Could this not be perhaps a more intentional error, perhaps containing this information? As it stands, it looks more like a bug that the application has a missing dependency rather than something intended.

**Comment by ashishdhingra** [comment]
This is perhaps a documentation issue and Readme needs to document possible dependency on `AWSSDK.SecurityToken`.

**Comment by normj** [comment]
This is one of the awkward parts of the SDK where we have a circular dependency because the AWS credentials resolution and types all exist in Core but some credential profiles require `AWSSDK.SecurityToken` or other service clients but those service clients  depend on core. This runtime dependency based approach is how we have solved the problem so far. I suspect we will need to revisit this design in the future as we try and add support for things like Native AOT which isn't going to like this approach.
