### ISSUE TITLE
5.1.1 breaks existing application using StringList

### ISSUE THREAD

**Issue by cfbao** [aws/aws-dotnet-extensions-configuration#156]
### Describe the issue

The new handling of StringList introduced by https://github.com/aws/aws-dotnet-extensions-configuration/pull/142 breaks existing apps that already consume StringList via this library.

Code that used to expect a comma separated string from IConfiguration (or equivalently via IOptions) now doesn't get expected values.

The new feature is neat, but it should've been in a major version update. If unlisting isn't practical, at least some warnings in the docs would be appreciated.

### Links

https://github.com/aws/aws-dotnet-extensions-configuration/blob/master/README.md

**Comment by ashishdhingra** [comment]
Updating readme should be feasible for now. Needs review with the team.

**Comment by jeremiah-huston** [comment]
I would also like to express my team's concern about this. We were surprised to find that this release introduced a breaking change, as patch versions are typically reserved for bug fixes and minor improvements. The fact that some of our parameters that used to return strings were now returning null caused us a lot of confusion.

**Comment by peterrsongg** [comment]
Thank you for the report and sorry for the accidental breaking change. We've decided to do a major version bump and also unlist the impacted version, 5.1.1 to avoid any confusion.

**Comment by peterrsongg** [comment]
We've released version 6.0.0 and unlisted version 5.1.1.

**Comment by cfbao** [comment]
Thanks for unlisting and bumping the major version. I believe this sufficiently addressed this concern.
