### ISSUE TITLE
After updating from 6.1.0 to 6.1.1 loading data from param store takes 10s as oppose to 1s

### ISSUE THREAD

**Issue by Soniyck** [aws/aws-dotnet-extensions-configuration#174]
### Describe the bug

After upadting from 6.1.0 to 6.1.1 calling `builder.AddSystemsManager` takes approximately 10s. After 

### Expected Behavior

Calling `builder.AddSystemsManager` should take up to 1s

### Current Behavior

Calling `builder.AddSystemsManager` takes up to 10s

### Reproduction Steps

Add nuget dependency `<PackageReference Include="Amazon.Extensions.Configuration.SystemsManager" Version="6.1.1" />` and load parameter store configuration in program.cs

```csharp
    private static void AddParameterStorePath(IConfigurationBuilder builder, string path, string storeRegion, string storeAccessKey, string storeSecretKey)
    {
        builder.AddSystemsManager(configureSource =>
        {
            // Parameter Store prefix to pull configuration data from.
            configureSource.Path = path;

            // Reload configuration data every 15 days.
            configureSource.ReloadAfter = TimeSpan.FromDays(15);

            // Set credentials for the store
            var awsCredentials = new BasicAWSCredentials(storeAccessKey, storeSecretKey);
            configureSource.AwsOptions = new Amazon.Extensions.NETCore.Setup.AWSOptions()
            {
                Region = RegionEndpoint.GetBySystemName(storeRegion),
                Credentials = awsCredentials,
            };

            // Set the configuration data as optional.
            configureSource.Optional = true;
        });
    }
```

### Possible Solution

Tried debugging this, seems like the app gets stuck while initializing client in ClientFactory class from dependency `Amazon.Extensions.NETCore.Setup`, downgrading the nuget to previous version should fix that.

### AWS .NET SDK and/or Package version used

AWSSDK.Core 3.7.304.24

### Targeted .NET Platform

.NET 8

### Operating System and version

Ubuntu 22.04

**Comment by ashishdhingra** [comment]
- `Amazon.Extensions.Configuration.SystemsManager` version `6.1.1` bumped the version of `AWSSDK.Extensions.NETCore.Setup` to `3.7.300` per commit https://github.com/aws/aws-dotnet-extensions-configuration/commit/2d494bb833650f2c60645e20fd282ccbe6a4c56c.
- `AWSSDK.Extensions.NETCore.Setup` version `3.7.300` was updated to pick the `3.7.300` version of the SDK per commit https://github.com/aws/aws-sdk-net/commit/43b851ae7981005e8f188c9d126fcc71fac311c0 ([PR]https://github.com/aws/aws-sdk-net/pull/3101)).

**Comment by bhoradc** [comment]
Hi @Soniyck, 

Thank you reporting the issue. Using below code sample (ASP.NET, .NET 8) with packages `Amazon.Extensions.Configuration.SystemsManager 6.1.1` and `AWSSDK.Core 3.7.304.24` I am unable to reproduce the delay. 

Program.cs
```c#
public static void Main(string[] args)
{
    //created parameter `dotnetParameterName` in Parameter Store via console
    string path = "/";
    string storeRegion = "us-east-1";
    string storeAccessKey = "xxxx";
    string storeSecretKey = "xxxx";

    var builder = WebApplication.CreateBuilder(args);

    var timeCounter = new Stopwatch();

    timeCounter.Start();

    AddParameterStorePath(builder.Configuration, path, storeRegion, storeAccessKey, storeSecretKey);

    builder.Services.AddControllers();

    var app = builder.Build();

    app.UseHttpsRedirection();
    app.UseAuthorization();
    app.MapControllers();

    //Calculate elapsed time 
    timeCounter.Stop();
    var elapsedTime = timeCounter.ElapsedMilliseconds;
    Console.WriteLine("ElapsedTime is " + elapsedTime);

    app.Run();
}

private static void AddParameterStorePath(IConfigurationBuilder builder, string path, string storeRegion, string storeAccessKey, string storeSecretKey)
{
    builder.AddSystemsManager(configureSource =>
    {
        configureSource.Path = path;
        configureSource.ReloadAfter = TimeSpan.FromDays(15);
        configureSource.AwsOptions = new Amazon.Extensions.NETCore.Setup.AWSOptions()
        {
            Region = RegionEndpoint.GetBySystemName(storeRegion),
            Credentials = new BasicAWSCredentials(storeAccessKey, storeSecretKey)
        };
        configureSource.Optional = true;
    });
}
```

I would get `ElapsedTime` around 600ms - 700ms with both `Amazon.Extensions.Configuration.SystemsManager` 6.1.0 and 6.1.1.  

Can you kindly provide more details on loading the parameter store in your application? And are you consistently able to see the 10s delay with version 6.1.1?

Regards, 
Chaitanya
