### ISSUE TITLE
Permissions section in readme.md incorrect. Required permission is ssm:GetParametersByPath not ssm:GetParameters

### ISSUE THREAD

**Issue by EdwardNickson** [aws/aws-dotnet-extensions-configuration#175]
### Describe the issue

The permissions section in the Readme.md states that the extension requires the `ssm:GetParameters` permission to work. This is incorrect, it requires the `ssm:GetParametersByPath` permission.

Your implementation calls client.GetParametersByPathAsync() not client.GetParameters():
[SystemsManagerProcessor.cs GetParametersByPathAsync()](https://github.com/aws/aws-dotnet-extensions-configuration/blob/aa02b6ee4e4139d6a4f84b1b0742291c8c786c33/src/Amazon.Extensions.Configuration.SystemsManager/Internal/SystemsManagerProcessor.cs#L64)

### Links

https://github.com/aws/aws-dotnet-extensions-configuration/blob/master/README.md#parameter-store

**Comment by ashishdhingra** [comment]
Verified by running the sample in this repository after creating test IAM user. Indeed, the permission should be `ssm: GetParametersByPath`.
