### ISSUE TITLE
Better IConfigurationRoot::GetDebugView() support

### ISSUE THREAD

**Issue by benmccallum** [aws/aws-dotnet-extensions-configuration#177]
### Describe the feature

Currently the source of a config value that comes from this provider is written as `SystemsManagerConfigurationProvider`.

Other providers like the file system one, will write the file name.

Presumably there's something more that can be done in the `SystemsManagerConfigurationProvider` to make that better, specifically to write things like the AWS account id, path, filter, etc.) to assist when debugging complex hierarchies of configs.

It'd just be a matter of seeing where they pull that value from and supplementing it.

### Use Case

Debugging.

### Proposed Solution

Will come back and propose something, but for now just trying to log this and will come back. Might even implement it when I have a sec.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

amazon.extensions.configuration.systemsmanager\6.1.1

### Targeted .NET Platform

.NET 7

### Operating System and version

Windows 11 / Linux containers

**Comment by bhoradc** [comment]
This needs to be reviewed with the team.

**Comment by bhoradc** [comment]
Hi @benmccallum, 

Thanks for submitting the feature request. Team believes this is a valid feature request, but would like to gather more specifics on what type of details you are looking to include?

While the feature request gets prioritized, feel free to contribute your PR and the team will be happy to review it. 

Regards, 
Chaitanya
