### ISSUE TITLE
Document how to use TOptions/binding with hierarchy

### ISSUE THREAD

**Issue by jchoca** [aws/aws-dotnet-extensions-configuration#182]
### Describe the issue

I can't seem to find anywhere where it's documented that hierarchical keys should be delimited by a slash. For example, say I have something like the following:

```csharp
public class ApplicationSettings
{
    public SqlSettings PrimaryDbRead { get; set; }
    public SqlSettings PrimaryDbWrite { get; set; }
}

public class SqlSettings
{
    public string Server { get; set; }
    public string DatabaseName { get; set; }
    public string User { get; set; }
    public string Password { get; set; }
}
```

then in my `Program.cs` file I have `services.Configure<ApplicationSettings>(config);`. If I were mapping that to an environment variable, I would use `PrimaryDbRead__Password` as a key. Not knowing any better, I might use an SSM param like `/my-application/PrimaryDbRead__Password`, but that doesn't work and instead needs to be `/my-application/PrimaryDbRead/Password`. It would probably be better if both just worked, but having this documented is better than nothing. Is this documented anywhere?

### Links

https://github.com/aws/aws-dotnet-extensions-configuration/blob/master/README.md

**Comment by bhoradc** [comment]
Hello @jchoca, 

Thank you for submitting the documentation change request. Our team will review the behaviour you've described and work on documenting the expected approach for structuring configuration keys. 

We appreciate you highlighting this, and we'll make the necessary changes accordingly.

Regards, 
Chaitanya

**Comment by ashishdhingra** [comment]
Readme updated with added sections for [Hierarchical configuration data](https://github.com/aws/aws-dotnet-extensions-configuration?tab=readme-ov-file#hierarchical-configuration-data).

**Comment by jchoca** [comment]
Thank you!
