### ISSUE TITLE
How do you use this in Lamba only?

### ISSUE THREAD

**Issue by ThomasJaeger** [aws/aws-dotnet-extensions-configuration#25]
This is nice for ASP.NET Core but how do I actually use this in a simple lambda that needs to access it's connection string, for example?

**Comment by normj** [comment]
@tonysneed actually just wrote up a [blog post](https://blog.tonysneed.com/2018/12/16/add-net-core-di-and-config-goodness-to-aws-lambda-functions/) on how to add .NET Core configuration and DI into a Lambda function. 

You can follow that and then just add this provider to the list of providers in the `ConfigurationBuilder`

**Comment by tonysneed** [comment]
@ThomasJaeger I worked up an example that uses EF with a connection string in config to access a database: https://github.com/tonysneed/net-core-lambda-di-config-ef

I am tweaking it a today, but the most important bit it [this](https://github.com/tonysneed/net-core-lambda-di-config-ef/blob/master/NetCoreLambda/Function.cs#L55):

```csharp
// Register DbContext class
serviceCollection.AddTransient(provider =>
{
    var configService = provider.GetService<IConfigurationService>();
    var connectionString = configService.GetConfiguration()[$"ConnectionStrings:{nameof(SampleDbContext)}"];
    var optionsBuilder = new DbContextOptionsBuilder<SampleDbContext>();
    optionsBuilder.UseSqlServer(connectionString);
    return new SampleDbContext(optionsBuilder.Options);
});
```

**Comment by tonysneed** [comment]
@ThomasJaeger Here is a better example: https://github.com/tonysneed/net-core-lambda-dep-resolver

Just add a call to `AddSystemsManager` in the `ConfigureServices` method:

```csharp
private void ConfigureServices(IServiceCollection services)
{
    // Add Configuration to DI system
    services.AddConfiguration(builder =>
    {
        // Get ASPNETCORE_ENVIRONMENT
        var environment = Environment.GetEnvironmentVariable(
            Constants.EnvironmentVariables.AspnetCoreEnvironment)
            ?? Constants.Environments.Production;

        // Build config
        return builder
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
            .AddJsonFile($"appsettings.{environment}.json", optional: true)
            .AddSystemsManager("/my-cool-app")
            .AddEnvironmentVariables()
            .Build();
    });
}
```

**Comment by normj** [comment]
Closing as I believe this has been answered.
