### ISSUE TITLE
warning NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead.

### ISSUE THREAD

**Issue by KenHundley** [aws/aws-dotnet-extensions-configuration#27]
I noticed this warning today when testing Issue #26. 
`warning NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead.`
https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5125

It appears that Microsoft is depricating license url because it's mutable after the package is created, and they are switching a different model where you'll directly imbed the license into the package or link to license text hosted by Nuget.
https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg

Nuget Apache 2.0 license: https://licenses.nuget.org/Apache-2.0

It seems like an easy modification to resolve this warning, but since this is licensing related I'm sure you prefer to handle the resolution.

**Comment by KenHundley** [comment]
Closing as it's covered in PR

**Comment by sstevenkang** [comment]
Re-opening this as we reverted the change with https://github.com/aws/aws-dotnet-extensions-configuration/commit/47734b564607c97b8cad22f25f24b3d6b874123e

**Comment by ashishdhingra** [comment]
Fixed in commit https://github.com/aws/aws-dotnet-extensions-configuration/commit/981b2ccb65477b9fe194c11570a475b1bc107508
