### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by richardgavel** [aws/aws-dotnet-extensions-configuration#30]
Add some Verbose/Debug level logging to the provider. Probably would have to provide an ILogger via the extension method.

Examples: Maybe the key/values pairs being added to the combined Configuration, TTL? Interactions around parameter store.

**Comment by ExcaliburVT** [comment]
Definitely have to agree with this.  I'm having trouble right now with this extension not loading configuration at all.  Something is happening but its totally hidden.  I've literally got two different versions of code, the first one loads properly the other doesn't and no code has changed that should impact the loading of the settings.  We DID just introduce a new 3rd party library but its loaded later in the startup.  Bottom line is that without some logging we don't have any way to determine what is really going wrong.
