### ISSUE TITLE
Testing via net472

### ISSUE THREAD

**Issue by koraybalci** [aws/aws-dotnet-extensions-configuration#34]
Hi, 

The integration tests I am working on right now is around an internal wrapper lib for your configuration extension and the tests are very similar to yours (in this repos' [tests folder here](https://github.com/aws/aws-dotnet-extensions-configuration/blob/master/test/Amazon.Extensions.Configuration.SystemsManager.Integ/ConfigurationBuilderIntegrationTests.cs)).

As we are migrating our old net472 code to dotnet standard/core gradually, we have been targeting our test projects to both net472 and netcoreapp2.0 like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.2;net472</TargetFrameworks>
```

Although integration test that retrieves values from aws are successful for _netcoreapp2_ target, the same test fails for _net472_.

Would you have any insights, what am I missing? I should be able to link your lib in a net472 lib, right?

**Comment by sstevenkang** [comment]
Could you provide more information like a minimal repro?  Also, are you sure your credentials are being resolved correctly?  There's nothing much here for us to start investigating.

**Comment by koraybalci** [comment]
Hi there, 

It is reproducible with the integration test projects in your repo as well. Just modify Amazon.Extensions.Configuration.SystemsManager.Integ.csproj file to target net472 along with netcore like this (modify line 4);

`
<TargetFrameworks>netcoreapp2.1;net472</TargetFrameworks>
`

Once you build and execute tests (you might need to restart vs), you'll see tests for netcoreapp targeted version will succeed whereas net472 ones will fail. Here is my (NCrunch) test execution output below:

![image](https://user-images.githubusercontent.com/1880390/55690568-a05f8a00-59d6-11e9-8684-a59ea94a39e9.png)

Let me know if you need further details & thanks for looking into it.

**Comment by KenHundley** [comment]
I tested this locally and I don't get any failures
![image](https://user-images.githubusercontent.com/2495780/55691863-868b5c00-5970-11e9-975d-b20009f166c4.png)

**Comment by koraybalci** [comment]
Ok, here is ReSharper output from my box:

![image](https://user-images.githubusercontent.com/1880390/55692850-ee808780-59ee-11e9-9aaa-44757596db0a.png)

Perhaps you can try checking out your repo to a fresh directory to replicate the issue?

**Comment by KenHundley** [comment]
Created a brand new checkout and still no issues
![image](https://user-images.githubusercontent.com/2495780/55760170-5784f100-5a29-11e9-9b2d-39a50e636328.png)

**Comment by koraybalci** [comment]
Well, sounds like it's a stalemate.. I'll close the issue (although the problem on our end persists).
