### ISSUE TITLE
Add filter by Parameter Label 

### ISSUE THREAD

**Issue by zahycs** [aws/aws-dotnet-extensions-configuration#43]
Hi, 
I couldn't find a way to use labels to filter parameters,  with the Path, a Label could be used to retrieve a specific labeled version of parameters set, for example a set of parameters labeled with a specific release version.

**Suggested change:** 

1. Add `Label` property to `SystemsManagerConfigurationSource` . 
2. Use the Label if it is not null as a ParameterFiler in `GetParametersByPathRequest`
Something like this 
` var response = await client.GetParametersByPathAsync(new GetParametersByPathRequest
                    {
                        Path = Source.Path,
                        Recursive = true,
                        WithDecryption = true,
                        NextToken = nextToken,
                        ParameterFilters = CreateLabelFilter(Source.Label)
                    }).ConfigureAwait(false);`

`public static List<ParameterStringFilter> CreateLabelFilter(string label)
        {
            if (string.IsNullOrWhiteSpace(label))
                return null;
            return new List<ParameterStringFilter> { new ParameterStringFilter
            {
                Key="Label",
                Option="Equals",
                Values = new List<string>{label}
            }};
        }`

**Usage:**
` config.AddSystemsManager(configurationSource=>
                     {
                         configurationSource.Path = "mypath";
                         configurationSource.Optional = false;
                         configurationSource.ReloadAfter = TimeSpan.FromMinutes(10);
                         configurationSource.Label="release_v1.2.3"
                     });`

**Update** 
Maybe it's more helpful to add `ParameterFilters` property to `SystemsManagerConfigurationSource`  `ParameterFilters` would of type `List<ParameterStringFilter> `  , to keep it more open to the user?
- if any of these suggested changes is accepted I can create a PR.

**Comment by klaytaybai** [comment]
I think you should be able to use the label filter using the same method as in your CreateLabelFilter method.  Did you have issues with that?   

If adding to the SystemsManagerConfigurationSource, I think adding the Label property might be the better route for the sake of consistency with 'Path'.

**Comment by zahycs** [comment]
@klaytaybai  Thank you for your reply. 

I'm not sure if I got what you mean by : 

>  use the label filter using the same method ,

What I meant is that I couldn't find a  suitable overload of the method `AddSystemsManager` in `SystemsManagerExtensions`  to use  parameter filters, specifically a Label.

> If adding to the SystemsManagerConfigurationSource, I think adding the Label property might be the better route for the sake of consistency with 'Path'. ,

OK great, I have a working fork with the Label property added, it gives us exactly what we needed.

**Comment by normj** [comment]
PR was merged and shipped as part of version 1.2.0
