### ISSUE TITLE
consider removal of the Microsoft.Extensions.Configuration nuget reference

### ISSUE THREAD

**Issue by grahamehorner** [aws/aws-dotnet-extensions-configuration#46]
please consider removing the Microsoft.Extensions.Configuration nuget reference for the package; as this is not needed.  the package should only reference the Microsoft.Extensions.Configuration.Abstractions

**Comment by KenHundley** [comment]
The `SystemsManagerConfigurationProvider` is inherited from the `ConfigurationProvider` base class in `Microsoft.Extensions.Configuration`. This same implementation is in place for the other common providers like `JsonConfigurationProvider` (*.json), `EnvironmentVariablesConfigurationProvider`, etc.

Can you explain the issue you are encountering that would be sovled by using `Microsoft.Extensions.Configuration.Abstractions`?
