### ISSUE TITLE
Cannot retrieve SSM StringList as list of string

### ISSUE THREAD

**Issue by seroche** [aws/aws-dotnet-extensions-configuration#48]
Hi, 

We have created a parameter named `/Staging.Commom/Throttling/IpWhiteList` as a `StringList`.
Current value is `1.1.1.1,0.0.0.0,2.2.2.2`

The code below always return `null`:
```
Configuration.GetValue<IEnumerable<string>>("Throttling:IpWhiteList");
Configuration.GetValue<ICollection<string>>("Throttling:IpWhiteList");
Configuration.GetValue<IList<string>>("Throttling:IpWhiteList");
Configuration.GetValue<string[]>("Throttling:IpWhiteList");
Configuration.GetValue<StringListParameterValue>("Throttling:IpWhiteList");
```

The code below works fine:
```
Configuration.GetValue<string>("Throttling:IpWhiteList");
```

Since it's a string list in AWS SSM, we were expecting to get a collection of strings. Did we do something wrong?

Regards,
Seb

**Comment by KenHundley** [comment]
This extention is built around the `GetParametersByPrefix` SDK method. The value property of the `Parameter` class returned by this method is always just a string, regardless of the parameter type. So there would need to be logic added to inspect the type and transform those values to a different format. 

So as of now you would only be able to retrieve values with `Configuration.GetValue<string>`

**Comment by Toritos** [comment]
If this is the case, then this makes StringList redundant as you'd have to split it into a list yourself anyway, you may as well just use String.

**Comment by hammypants** [comment]
Still a major annoyance.
