### ISSUE TITLE
Sample Lambda custom runtime integration

### ISSUE THREAD

**Issue by holmesjr** [aws/aws-dotnet-extensions-configuration#55]
I've scoured the interwebs for an example of integrating the .Net Generic Host with a lambda using a 3.1 custom runtime. I haven't found one - all the examples assume that MVC is being used.

As the lambda bootstrap doesn't seem to work natively with the generic host interface, I'm using Host.CreateDefaultBuilder to build the appropriate host and then setting the IHost.Services up as a static field to access in the Lambda Handler. This all seems awful and if there's a better way to do it it's not documented anywhere. 

Is there a better way to get Config into a simple lambda without MVC?

**Comment by klaytaybai** [comment]
I'll work on getting you a sample soon.

**Comment by holmesjr** [comment]
If it will help, I can create a gist of what I currently have.

**Comment by ashishdhingra** [comment]
PR https://github.com/aws/aws-dotnet-extensions-configuration/pull/84 closed due to lack of activity. Closing the issue.
