### ISSUE TITLE
Lambda Dotnet Core Serverless App

### ISSUE THREAD

**Issue by genifycom** [aws/aws-dotnet-extensions-configuration#56]
Can you provide an example of how to use this with a Lambda Dotnet Core Serverless App please.

Do we add it in to the ConfigureServices?

**Comment by klaytaybai** [comment]
Please see my comment in [your other recent issue](https://github.com/aws/aws-dotnet-extensions-configuration/issues/57).

You will need to add a line to ConfigureServices.
Per the sample in this repo:
`services.Configure<Settings>(Configuration.GetSection("settings"));`
That assumes you have a model class (Settings) for your parameters found at 
`<root from LocalEntryPoint configuration>/settings`.
