### ISSUE TITLE
AddSystemsManager causes LocalEntryPoint to hang

### ISSUE THREAD

**Issue by genifycom** [aws/aws-dotnet-extensions-configuration#57]
I created a default "AWS Serverless Application" for Blueprint "ASP.NET Core Web App", loaded the Amazon.Extensions.Configuration.SystemsManager nuget package 
and modified the LocalEntryPoint.

`        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration(builder =>
                {
                    builder.AddSystemsManager("/pf");
                })
                .UseStartup<Startup>()
                .Build();`

I get this exception:
`This exception was originally thrown at this call stack:
	System.Net.Http.HttpClient.HandleFinishSendAsyncError(System.Exception, System.Threading.CancellationTokenSource)
	System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage>, System.Net.Http.HttpRequestMessage, System.Threading.CancellationTokenSource, bool)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.GetResult()
	System.Net.Http.HttpClient.GetStringAsyncCore(System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage>)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    ...
    [Call Stack Truncated]`

Would love to get the Parameter Store working but currently there is insufficient documentation for .NET Core 2.1 running in Lambda and Locally.

Tried https://github.com/aws/aws-dotnet-extensions-configuration but the page does not reflect the code we see in the template for "AWS Serverless Application" for Blueprint "ASP.NET Core Web App".

Also tried https://seroter.wordpress.com/2019/03/04/want-to-yank-configuration-values-from-your-net-core-apps-heres-how-to-store-and-access-them-in-azure-and-aws/ but this gives me the above exception.

Any help to get this going would be appreciated.

**Comment by klaytaybai** [comment]
I'm not sure why this is hanging for you.  I think there is a chance you don't have credentials or access to the intended parameter store (i.e. "/pf" in your code).  You should try verifying that your credentials are giving you access to that parameter store path independently of building this app as a good first step.

Using the AWS Serverless Application blueprint, I was not able to reproduce your problem.  By modifying the blueprint with the Settings class, the settings configuration line in Startup.ConfigureServices, and the WebHost Builder app configuration line, I was able to successfully retrieve Settings values if using the correct credentials and region.  I can post a sample app if necessary, but the configuration differences from a regular AWS Serverless Application setup are pretty much the same as in the sample app that already exists in this repo.

**Comment by genifycom** [comment]
Because I work with multiple clients in AWS, my credentials file has multiple profiles. If I do
aws sts get-caller-identity --profile pf
then I get the correct iam user. If I do not specify a profile then I get Unable to locate credentials as expected (I deliberately do not have a default).

I suspect that may have caused this. Thank you for your help.
