### ISSUE TITLE
ReloadAfter doesn't work well in Lambda (2)

### ISSUE THREAD

**Issue by monnecc** [aws/aws-dotnet-extensions-configuration#60]
I'd like to reopen this issue: https://github.com/aws/aws-dotnet-extensions-configuration/issues/17

I've been testing with this again and it still doesn't work. I've downloaded the code from the SDK and put tracing in, but the function doesn't reload it's configuration after the indicated time. I've downloaded the code and put tracing in and could confirm that configuration isn't reloaded as expected. The freeze of the lambda function means the reload timer (cancellation token) freezes as well. Eventually the config is reloaded, but it isn't predictable when.
I wouldn't mind waiting synchronously for the configuration to reload, if that's easier to build.

**Comment by klaytaybai** [comment]
I've reopened the original issue since it had a long chain of comments.  I'm going to close this one as a duplicate.
