### ISSUE TITLE
Upgrade aws-sdk-net packages to version with support for sts:AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by brianbakeratx** [aws/aws-dotnet-extensions-configuration#61]
AWS has added EKS support for [IAM Roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).

This new EKS feature requires an updated SDK that contains a new credential provider that calls sts:AssumeRoleWithWebIdentity.  It looks like aws-sdk-net 3.3.101 contains this change to support sts:AssumeRoleWithWebIdentity.

**Comment by overbit** [comment]
Any update on this?

**Comment by overbit** [comment]
Still problems here. 

`Unhandled exception. System.InvalidOperationException: Assembly AWSSDK.SecurityToken could not be found or loaded. This assembly must be available at runtime to use Amazon.Runtime.AssumeRoleAWSCredentials.
mysampleapp ---> System.IO.FileNotFoundException: Could not load file or assembly 'AWSSDK.SecurityToken, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

**Comment by sethfduke** [comment]
Upgrading to the 2.0.0 package and adding a reference to AWSSDK.SecurityToken fixed the issue.
