### ISSUE TITLE
SSM does not work with AWS X-Ray

### ISSUE THREAD

**Issue by DamirAinullin** [aws/aws-dotnet-extensions-configuration#62]
I added this project to solution in according to documentation.
I don't see X-Ray tracing for SSM client. And also I don't see SSM servive on X-Ray Service map. I suppose it is because IAmazonSimpleSystemsManagement client is created using reflection. I think there should be way to resolve IAmazonSimpleSystemsManagement using DI or implicit setting IAmazonSimpleSystemsManagement instance into the library.

**Comment by brianjbeach** [comment]
I assume you mean that you used `AWSSDKHandler.RegisterXRayForAllServices()`. If so, I see `SimpleSystemsManagement.GetParameterByPath` in my XRay trace. However, if you are tracing a Lambda function, Lambda does not capture trace details during the Initialization phase where this extension is likely running. So you should see SSM in your XRay trace from ASP.NET outside of Lambda, but you will not see it in Lambda. I typically run a few tests using the local entry point to optimize startup before publishing my Lambda function.  Anyway, I don't think this is a bug (of feature-request) in SSM.

**Comment by DamirAinullin** [comment]
Yes, I use AWS Lambda.

**Comment by ashishdhingra** [comment]
@DamirAinullin I was going through issue backlog and came across this feature request. Could you please confirm if this is still a valid feature request? [Instrumenting C# code in AWS Lambda](https://docs.aws.amazon.com/lambda/latest/dg/csharp-tracing.html) provides some information on how to use AWS Lambda with AWS X-Ray. Please let me know if it helps.

**Comment by mgorski-mg** [comment]
@ashishdhingra I think you can simply close this issue as it is not a feature request to this library.
This is just how Xray works with Lambda as @brianjbeach properly explained :)
Right @DamirAinullin?
