### ISSUE TITLE
Unable to retrieve ConnectionStrings

### ISSUE THREAD

**Issue by NicholasMata** [aws/aws-dotnet-extensions-configuration#76]
## The Question
I have followed this [guide](https://aws.amazon.com/blogs/developer/net-core-configuration-provider-for-aws-systems-manager/).

AWS Systems Manager parameters are 
`/philinq/ConnectionStrings/OAuthConnection`
`/philinq/ConnectionStrings/PhilinqConnection`

In my `Program.cs` I have the following
```csharp
Host.CreateDefaultBuilder(args)
.UseSerilog()
.ConfigureAppConfiguration((context, builder) =>
{
   builder.AddSystemsManager("/philinq");
})
 .ConfigureWebHostDefaults(webBuilder =>
{
   webBuilder.UseStartup<Startup>();
});
```

As far as credentials go I believe it is supposed to use the ones have configured for the aws cli. In the aws cli I am able to access both the parameters above.

In my `Startup.cs` I have the normal logic to get the ConnectionString from Configuration
```csharp
var philinqConnectionString = Configuration.GetConnectionString("PhilinqConnection");
var oauthConnectionString = Configuration.GetConnectionString("OAuthConnection");
```
Since `GetConnectionString` is shorthand for `GetSection("ConnectionStrings")[name]`

**However I keep getting null for both connection strings. Am I missing something?**

When I debug `Configuration` I do see the provider 
<img width="891" alt="Screen Shot 2020-09-20 at 2 32 01 PM" src="https://user-images.githubusercontent.com/8304095/93722810-4b71ee00-fb4e-11ea-99ee-ece8887cbcb2.png">

### Environment

* Build Version: 1.2.0
* OS Info: macOS Catalina
* Build Environment: VSCode + Terminal `dotnet`
* Targeted .NET Platform:  .Net Core 3.1

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @NicholasMata,

Good afternoon.

I tried to reproduce the issue using your code. However, it works perfectly fine, refer the below screenshots:

![Image 9-21-20 at 1 35 PM](https://user-images.githubusercontent.com/67916761/93818643-7cfebe00-fc0f-11ea-9c6a-1081c1b1f5f7.jpeg)

![Image 9-21-20 at 1 37 PM](https://user-images.githubusercontent.com/67916761/93818763-a4ee2180-fc0f-11ea-9e63-35f2778846ba.jpeg)


The only issue I see is that the System Manager parameters might have been created in a different region than what's configured in your `.aws/credentials` file (or other default fallback places). Please check your region configuration and ensure that it matches to where the parameters are actually created. Kindly confirm if this issue could be closed.

Thanks,
Ashish

**Comment by NicholasMata** [comment]
Sorry I haven't had time to test this lately. Weird thing is now it works without any corrections. Sorry I can't be more helpful to anyone else who encounters this issue. Maybe just wait a day and come back is my best guess.
