### ISSUE TITLE
ReloadAfter does not work in deployed MVC Web API 3.1

### ISSUE THREAD

**Issue by jaretts** [aws/aws-dotnet-extensions-configuration#79]
System Manager ReloadAfter works fine running this executable locally on development machine.

Unfortunately, the ReloadAfter functionality in SystemsManagerConfiguration does not work in our .NET solution running/deployed in AWS when the application is running inside a Docker container (default Microsoft/Alpine base image mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine) deployed to ECS/Fargate

In the AWS deployment Parameter values are loaded at startup but remain the same during the lifetime of the instance. 

The Parameter values are loaded at started up and then not reload when deployed in AWS. Locally the Parameters values are reloaded every 2 minutes as specified by call to ReloadAfter

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Similar to https://github.com/aws/aws-dotnet-extensions-configuration/issues/17

**Comment by ashishdhingra** [comment]
Hi @jaretts,

Good afternoon.

Looks like we have the similar issue https://github.com/aws/aws-dotnet-extensions-configuration/issues/17 which is already prioritized and queued. Hence closing this issue. If required, you can add yourself to watchlist of the other issue.

Thanks,
Ashish
