### ISSUE TITLE
SSO Credential Support - does not recognize SSO Tokens in AWS Credentials file

### ISSUE THREAD

**Issue by listylister** [aws/aws-dotnet-extensions-configuration#95]
## Description
We are using AWS CLI SSO Tokens in our aws .credentials file but they are not recognized as a supported way of authenticating to AWS and an exception message is shown to reflect this. I believe this is because this package is quite far behind the current AWSSDK.Core package version

## Reproduction Steps
Try to use an CLI SSO Token in credentials file and an exception is thrown indicating that SSO is not supported.

### Environment
version 2.1.0

## Resolution
Update this package to use the latest awssdk.core package (via updating AWSSDK.Extensions.NETCore.Setup to the latest version)

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @listylister,

Good afternoon.

Thanks for posting the issue. Could you please elaborate on how you are planning to use SSO tokens with Systems Manager in ASP.NET Core application? Based on similar issues, user has to execute `aws sso login` from AWS CLI before using these credentials via AWS .NET SDK.

Thanks,
Ashish

**Comment by listylister** [comment]
Hi, it's for local development purposes only. So we don't have to
copy/paste and auth tokens into the credentials file we plan to use as
tokens to authenticate our local development environment instead.

Hope that makes sense.

Thanks

**Comment by stevenholder** [comment]
I seem to be having a similar problem, when I do an `aws sso login --profile profieName` then I configure appsettings.json's profile to `profileName` nothing is loaded with exceptions being thrown around `AWSSDK.SSO` and `AWSSDK.SSOOIDC` missing.

Once I add those packages, the extension works as expected.

**Comment by listylister** [comment]
Afraid I get the same error, even after adding those packages...here is a screenshot - it just doesn't like the fact that default is an SSO profile.
![Capture](https://user-images.githubusercontent.com/3535862/125040792-f2008e80-e08f-11eb-987b-8c57e9bb68e3.PNG)

**Comment by stevenholder** [comment]
Yeah, one of my employees tried to use the project on his machine and was getting the same errors about missing types even though he had the packages I mentioned installed, then he updated the packages from 3.7.0.38 to 3.7.0.39 and then he was able to see values in the SecretsManager configuration section. Before that he would have a 1 minute timeout while the AWS API call blocked trying to load the configuration before the API would turn on.

**Comment by ashishdhingra** [comment]
[Amazon.Extensions.Configuration.SystemsManager 2.1.1](https://www.nuget.org/packages/Amazon.Extensions.Configuration.SystemsManager/2.1.1) released with the support for SSO credentials.
