### ISSUE TITLE
Config reload not occuring

### ISSUE THREAD

**Issue by jsauter** [aws/aws-dotnet-extensions-configuration#97]
## Description
When you set the TimeSpan to reload the configuration in the sample, the configuration does not reload.

## Reproduction Steps

1. Run the sample code, with timespans placed in for reload of configuration.  Provide an override level in the configuration:

`             config.AddSystemsManager($"/dotnet-aws-samples/systems-manager-sample/common", new System.TimeSpan(0, 0, 5) );
                    config.AddSystemsManager($"/dotnet-aws-samples/systems-manager-sample/{env.EnvironmentName}", new System.TimeSpan(0, 0, 5) );
   `

The reload of 5 seconds never happens if I update the value of environment named configurations.

It seems that if I replace the IOptions with IOptionsSnapshot, the reload works.

I am not sure if this is a change in dotnet core or not, but it no longer seems to work.

### Environment
* Build Version: 2.1.1
* OS Info: OSX - 10.15.7
* Build Environment: VSCode
* Targeted .NET Platform:  2.1 (according to sample) but we see same results in 5.0

## Resolution

I guess the sample should be upgraded to use IOptionsSnapshot and maybe some documentation around that.  Overall, the configuration management still works, but there is a bit of a rabbit hole to figure out the solution.  I can for and create a PR if you like.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Another possible related issue https://github.com/aws/aws-dotnet-extensions-configuration/issues/17.

@jsauter Feel free to submit a PR which could be reviewed by development team.

**Comment by KenHundley** [comment]
Hey @jsauter, that's intended behavior. 

You can see the details for IOptions and IOptionsSnapshot at [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0#options-interfaces)

Specifically the lines:

IOptions<TOptions>:
- Does not support:
  - **Reading of configuration data after the app has started.**

IOptionsSnapshot<TOptions>:
- **Use IOptionsSnapshot to read updated data**.

**Comment by jsauter** [comment]
@KenHundley I have not tested this level yet, do the IOptionsSnapshot trigger a SSM query on each request, or are they updating from the SystemsManager which is scheduled to reload via the reloadAfter parameter?

**Comment by KenHundley** [comment]
> ed this level yet, do the IOptionsSnapshot trigger a SSM query on each request, or are they updating from the SystemsManager which is scheduled to reload via the reloadAfter parameter?

It's kind of both from my understanding. There is a "pool" of data from all the configs that's maintained. The reload only updates on the supplied schedule and updates that "pool" of data with the new values. The IOptions will only read that pool at startup and creates a singleton. The IOptionsSnapshot will read that pool everytime the IOC asks for a new instance. 

So basically the SSM reader will run on the schedule, but the IOptionsSnapshot will be created and read that data on every request

**Comment by artempaskhin** [comment]
Good package BUT,
at https://github.com/aws/aws-dotnet-extensions-configuration/blob/9b12af807a7d595fb8f990d2e48c4551f91022c2/src/Amazon.Extensions.Configuration.SystemsManager/SystemsManagerConfigurationProvider.cs#L70

```
  ChangeToken.OnChange(() =>
                {
                    var cancellationTokenSource = new CancellationTokenSource(source.ReloadAfter.Value);
                    var cancellationChangeToken = new CancellationChangeToken(cancellationTokenSource.Token);
                    return cancellationChangeToken;
                }, async () =>
```
There is a bug here.
"cancellationChangeToken" will be recycled by GC
I suggest for Author to borrow timed reloading logics from here
https://github.com/Wallsmedia/DotNetCore.Azure.Configuration.KvSecrets/blob/master/src/AzureKvConfigurationProvider.cs
it should send also notifications "OnReload();" as well.

**Comment by Kralizek** [comment]
I have the same issue and I'm using `IOptionsSnapshot<T>`.

Here is my short repro (written using .NET 6.0):

Source:
```csharp
using Amazon;
using Amazon.Extensions.NETCore.Setup;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

var aws = new AWSOptions {Region = RegionEndpoint.EUWest1 };

var builder = new ConfigurationBuilder();
builder.AddSystemsManager("/ParameterStoreReload/TestApp", aws, TimeSpan.FromSeconds(1));

var configuration = builder.Build();

var services = new ServiceCollection();

services.AddOptions();

services.AddTransient<Service>();
services.Configure<ServiceOptions>(configuration);

var sp = services.BuildServiceProvider();

while (true)
{
    var svc = sp.GetRequiredService<Service>();

    svc.PrintValue();

    await Task.Delay(TimeSpan.FromMilliseconds(500));
}

public class Service
{
    private readonly IOptionsSnapshot<ServiceOptions> _options;

    public Service(IOptionsSnapshot<ServiceOptions> options)
    {
        _options = options ?? throw new ArgumentNullException(nameof(options));
    }

    public void PrintValue()
    {
        Console.WriteLine($"{Guid.NewGuid():D}: {_options.Value.Value}");
    }
}

public class ServiceOptions
{
    public int Value { get; set; }
}
```

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.0" />
    <PackageReference Include="Amazon.Extensions.Configuration.SystemsManager" Version="3.0.0" />
    <PackageReference Include="AWSSDK.Extensions.NetCore.Setup" Version="3.7.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="6.0.0" />
  </ItemGroup>

</Project>
```

Output:
```
8b45e161-4de5-40fe-8a01-d9f637c0b94c: 42
3adfe477-8831-4bd3-9afb-79100f8d8a0f: 42
37300fcd-e002-44de-a1e3-4432dd5ddd2f: 42
a9a3869b-45e6-42fd-8e8b-382135c0e227: 42
<< change value in console >>
5d15720a-c6b6-4a22-857e-cc3dcb5b26b0: 42
ced37d62-ea12-40ea-aa3c-b90a72168f70: 42
a6daf888-3917-4afa-8eb2-0ddefe392665: 42
95d903e3-8b52-4744-8fb1-2a1ab632fc43: 42
```

**Comment by Kralizek** [comment]
@ashishdhingra when you have time, can you confirm the comment above is able to reproduce the issue?

**Comment by sahilbatra** [comment]
Hi all , I am facing similar issue while fetching values from AppConfig , I am using IOptionSnapshot in my configuration object but its still not updating the values after reload timespan. When I checked Fiddler to trace the background calls , I can see that new API calls are definitely made in background to fetch latest configuration from AWS after specified reload interval ,  but those calls are not getting any data back . It gives 200 response from AWS API but with empty json response body . Only the first call brings back json response from AWS API call, subsequent calls return empty response. Any ideas around this ?

**Comment by ashishdhingra** [comment]
> ```
> Microsoft.Extensions.DependencyInjection
> ```

@Kralizek I tested using the code above. The ConfigReload happened when examined via Fiddler:
- Initial value was `52`.
![Screenshot 2023-05-03 at 11 35 24 AM](https://user-images.githubusercontent.com/67916761/236012136-d4baae9a-154d-45e6-9cb4-c7c2d0453bb1.png)

- Then changed the value to `100` in Systems Manager parameter store to `100`. Fiddler displayed the call with updated response from SSM.
![Screenshot 2023-05-03 at 11 35 52 AM](https://user-images.githubusercontent.com/67916761/236012149-e0dcc82c-efb6-47ae-8196-660f7c36f14e.png)

The library code is reloading the value, but somehow, it is not reflected in `IOptionsSnapshot` in above code. Need to investigate more from .NET perspective, doesn't appear to be a bug with this library.

**Comment by Kralizek** [comment]
@ashishdhingra great finding about the scope in the console application! Should I update my repro code to reflect it for future reference?

**Comment by thnam1410** [comment]
Hi, I've a little bit related issue when using `AddSystemManager()` and `ReloadAfter` configuration with `IOptionMonitor`. Seems like the reload after will only work with `IOptionSnapshot`. Does anyone know how to make it trigger `IOptionMonitor` to recognize the reload?

Sample code:

```csharp

builder.Services.Configure<OptionType>(options =>
{
    var section = builder.Configuration.GetSection(OptionType.Section);

    options.Key = section.Value!;
});

builder.Configuration.AddSystemsManager(source =>
{
    source.Path = "{{YourPath}}";
    source.ReloadAfter = TimeSpan.FromSeconds(15);
    source.OnLoadException = exceptionContext =>
    {
        Log.Error(exceptionContext.Exception, "Error while loading parameters from System Manager!");
    };
});

builder.Services.AddHostedService<Worker>();
```

```csharp
// Worker.cs

public class Worker: BackgroundService
{
    private readonly ILogger<Worker> _logger;
    private readonly IServiceProvider _serviceProvider;

    public Worker(ILogger<Worker> logger, IServiceProvider serviceProvider)
    {
        _logger = logger;
        _serviceProvider = serviceProvider;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            using var scope = _serviceProvider.CreateScope();
            var snapshot = scope.ServiceProvider.GetRequiredService<IOptionsSnapshot<OptionType>>();
            var monitor = scope.ServiceProvider.GetRequiredService<IOptionsMonitor<OptionType>>();

            _logger.LogInformation("Snapshot value: {Value}", snapshot.Value.Key);
            _logger.LogInformation("Monitor value: {Value}", monitor.CurrentValue.Key);
        
            await Task.Delay(5000, stoppingToken);
        }
       
    }
}

```
